version: "3"

tasks:
    build:
        desc: Build the app
        cmds:
        - GOFLAGS=-mod=mod go build -o /usr/local/bin/trello-discord-integration .

    run: 
        desc: Run the app
        cmds:
        - GOFLAGS=-mod=mod go run .